<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>0Chain S3 CLI System tests [master/37eb207a] ran against [dev-5.devnet-0chain.net] at [2024-07-17_17.28.59]</title>
    <style type="text/css">
        body {
            font-family: sans-serif;
            background-color: #f3f3f3;
            border-top: 2px #dee6e8 solid;
            margin: 0;
        }

        div.pageHeader span.projectTitle {
            font-family: serif;
            font-size: 2em;
            padding-left: 56px;
            padding-top: 80px;
            display: block;
            color: #a5a5a5;
            text-shadow: 0 -1px 1px white;
        }

        div.pageHeader div.testStats {
            position: absolute;
            top: 7px;
            right: 52px;
            font-size: 0.8em;
            color: #a2a2a2;
        }

        div.pageHeader div.testStats span.indicator {
            font-size: 2em;
            position: relative;
            top: 5px;
            text-shadow: 0 1px 0 white;
        }

        div.pageHeader div.testStats span strong {
            margin-right: 16px;
        }

        div.pageHeader div.testStats span.total {
            border-right: 1px #afafaf dotted;
            background: #8298af;
        }

        div.pageHeader div.testStats span.passed {
            border-right: 1px #afafaf dotted;
            background: #6fca83;
        }

        div.pageHeader div.testStats span.skipped {
            background: #bababa;
        }

        div.pageHeader div.testStats span.failed {
            background: #ff7676;
        }

        div.pageHeader div.testStats span {
            margin-right: 1px;
            height: 55px;
            padding: 20px 8px 18px;
            color: white;
        }

        div.pageHeader .testGroupsTitle {
            margin: 16px 32px 8px 40px;
            font-size: 0.9em;
            color: darkgrey;
            display: inline-block;
        }

        div.pageHeader .testExecutionDate {
            display: inline-block;
            position: absolute;
            right: 10px;
            margin: 14px 32px 8px 40px;
            color: #9e9e9e;
            font-size: 0.9em;
        }

        .testReportContainer {
            padding: 0 32px 32px 32px;
        }

        .cardContainer {
            padding: 16px 16px 16px;
            box-shadow: 0 4px 4px #d4d4d4;
            background-color: white;
        }

        #testResults {
            display: flex;
            flex-wrap: wrap;
        }

        .testResultGroup {
            width: 24px;
            height: 24px;
            background-color: #43c143;
            margin-left: 1px;
            margin-bottom: 1px;
            box-sizing: border-box;
        }

        .testResultGroup.selected {
            border: 1px white solid;
            background-color: black !important;
        }

        .testResultGroup.skipped {
            border: 2px gray solid;
        }

        .testResultGroup.failed {
            background-color: red;
        }

        .cardContainer.testGroupList,
        .cardContainer.testDetail {
            margin-top: 16px;
            padding: 16px;
        }

        .cardContainer.testGroupList {
            color: #9c9c9c;
            padding: 0;
        }

        .cardContainer.testGroupList .testGroupRow {
            cursor: default;
            border-bottom: 1px #dadada dotted;
        }

        .cardContainer.testGroupList .testGroupRow span.testStatus {
            font-size: 1.2em;
            font-weight: bold;
            color: #139e13;
            pointer-events: none;
            display: inline-block;
            overflow: hidden;
            float: left;
            padding-top: 10px;
            padding-left: 20px;
            padding-right: 12px;
        }

        .cardContainer.testGroupList .testGroupRow span.testStatus.skipped {
            color: gray;
        }

        .cardContainer.testGroupList .testGroupRow span.testStatus.failed {
            color: red;
        }

        .cardContainer.testGroupList .testGroupRow span.testTitle {
            font-size: 0.9em;
            padding: 12px 0 10px;
            display: inline-block;
            pointer-events: none;
            color: #525252;
            text-overflow: ellipsis;
            overflow: hidden;
            width: calc(100% - 110px);
        }

        .cardContainer.testGroupList .testGroupRow span.testDuration {
            pointer-events: none;
        }

        .cardContainer.testGroupList .testGroupRow {
            position: relative;
            border-left: 4px #43c143 solid;
        }

        .cardContainer.testGroupList .testGroupRow.skipped {
            color: gray;
            border-left: 4px gray solid;
        }

        .cardContainer.testGroupList .testGroupRow.failed {
            color: red;
            border-left: 4px red solid;
        }

        .cardContainer.testGroupList .testGroupRow:hover {
            background-color: #fffaea;
            transition: 0.250s;
        }

        .cardContainer .testOutput {
            padding: 8px 16px 24px 16px;
        }

        .cardContainer .console {
            display: block;
            font-family: monospace;
            padding: 10px;
            background-color: #424242;
            color: #1aff00;
            border-bottom: 1px #1aff00 dotted;
            overflow: auto;
            font-size: 1.1em;
        }

        .cardContainer .testOutput .testDetail {
            border-bottom: 1px #d0d0d0 solid;
            padding: 16px;
            background-color: #e6e6e6;
            border-radius: 0 0 4px 4px;
            color: dimgrey;
            font-size: 0.8em;
        }

        .cardContainer .console.skipped{
            color: #d9d9d9;
        }

        .cardContainer .console.failed {
            color: #ffb2b2;
        }

        .cardContainer .testDuration {
            position: absolute;
            top: 5px;
            right: 8px;
            text-align: right;
            padding-right: 8px;
            box-sizing: border-box;
        }
    </style>
</head>
<body>
<div class="pageHeader">
    <span class="projectTitle">0Chain S3 CLI System tests [master/37eb207a] ran against [dev-5.devnet-0chain.net] at [2024-07-17_17.28.59]</span>
    <div class="testStats">
        <span class="total"><span class="indicator">&boxbox;</span> Total: <strong>33</strong>Duration: <strong>7ms</strong>
        </span><span class="passed"><span class="indicator">&check;</span> Passed: <strong>0</strong>
        </span><span class="skipped"><span class="indicator">&dash;</span> Skipped: <strong>0</strong>
        </span><span class="failed"><span class="indicator">&cross;</span> Failed: <strong>33</strong>
        </span>
    </div>
    <span class="testGroupsTitle">Test Groups:</span>
    <span class="testExecutionDate">July 17, 2024 18:00:07</span>
</div>
<div class="testReportContainer">
    <div class="cardContainer">
        <div id="testResults">
            
                <div class="testResultGroup failed " id="0"></div>
            
                <div class="testResultGroup failed " id="1"></div>
            
                <div class="testResultGroup failed " id="2"></div>
            
                <div class="testResultGroup failed " id="3"></div>
            
                <div class="testResultGroup failed " id="4"></div>
            
                <div class="testResultGroup failed " id="5"></div>
            
                <div class="testResultGroup failed " id="6"></div>
            
                <div class="testResultGroup failed " id="7"></div>
            
                <div class="testResultGroup failed " id="8"></div>
            
                <div class="testResultGroup failed " id="9"></div>
            
                <div class="testResultGroup failed " id="10"></div>
            
                <div class="testResultGroup failed " id="11"></div>
            
                <div class="testResultGroup failed " id="12"></div>
            
                <div class="testResultGroup failed " id="13"></div>
            
                <div class="testResultGroup failed " id="14"></div>
            
                <div class="testResultGroup failed " id="15"></div>
            
                <div class="testResultGroup failed " id="16"></div>
            
                <div class="testResultGroup failed " id="17"></div>
            
                <div class="testResultGroup failed " id="18"></div>
            
                <div class="testResultGroup failed " id="19"></div>
            
                <div class="testResultGroup failed " id="20"></div>
            
                <div class="testResultGroup failed " id="21"></div>
            
                <div class="testResultGroup failed " id="22"></div>
            
                <div class="testResultGroup failed " id="23"></div>
            
                <div class="testResultGroup failed " id="24"></div>
            
                <div class="testResultGroup failed " id="25"></div>
            
                <div class="testResultGroup failed " id="26"></div>
            
                <div class="testResultGroup failed " id="27"></div>
            
                <div class="testResultGroup failed " id="28"></div>
            
                <div class="testResultGroup failed " id="29"></div>
            
                <div class="testResultGroup failed " id="30"></div>
            
                <div class="testResultGroup failed " id="31"></div>
            
                <div class="testResultGroup failed " id="32"></div>
            
        </div>
    </div>
    <div class="cardContainer testGroupList" id="testGroupList"></div>
</div>
<script type="application/javascript">
    /**
 * @typedef TestStatus
 * @property {string} TestName
 * @property {string} Package
 * @property {number} ElapsedTime
 * @property {Array.<string>} Output
 * @property {boolean} Passed
 * @property {boolean} Skipped
 */
class TestStatus {}

/**
 * @typedef TestGroupData
 * @type {object}
 * @property {string} FailureIndicator
 * @property {string} SkippedIndicator
 * @property {Array.<TestStatus>}
 */
class TestGroupData {}

/**
 * @typedef TestResults
 * @type {Array.<TestGroupData>}
 */
class TestResults extends Array {}

/**
 * @typedef SelectedItems
 * @property {HTMLElement|EventTarget} testResults
 * @property {String} selectedTestGroupColor
 */
class SelectedItems {}

/**
 * @typedef GoTestReportElements
 * @property {TestResults} data
 * @property {HTMLElement} testResultsElem
 * @property {HTMLElement} testGroupListElem
 */
class GoTestReportElements {}


/**
 * Main entry point for GoTestReport.
 * @param {GoTestReportElements} elements
 * @returns {{testResultsClickHandler: testResultsClickHandler}}
 * @constructor
 */
window.GoTestReport = function (elements) {
  const /**@type {SelectedItems}*/ selectedItems = {
    testResults: null,
    selectedTestGroupColor: null
  }

  function addEventData(event) {
    if (event.data == null) {
      event.data = {target: event.target}
    }
    return event
  }


  const goTestReport = {
    /**
     * Invoked when a user clicks on one of the test group div elements.
     * @param {HTMLElement} target The element associated with the test group.
     * @param {boolean} shiftKey If pressed, all of test detail associated to the test group is shown.
     * @param {TestResults} data
     * @param {SelectedItems} selectedItems
     * @param {function(target: Element, data: TestResults)} testGroupListHandler
     */
    testResultsClickHandler: function (target,
                                       shiftKey,
                                       data,
                                       selectedItems,
                                       testGroupListHandler) {

      if (target.classList.contains('testResultGroup') === false) {
        return
      }
      if (selectedItems.testResults != null) {
        let testResultsElement = /**@type {HTMLElement}*/ selectedItems.testResults
        testResultsElement.classList.remove("selected")
        testResultsElement.style.backgroundColor = selectedItems.selectedTestGroupColor
      }
      const testGroupId = /**@type {number}*/ target.id
      if ((target.id === undefined)
        || (data[testGroupId] === undefined)
        || (data[testGroupId]['TestResults'] === undefined)) {
        return
      }
      const testResults = /**@type {TestResults}*/ data[testGroupId]['TestResults']
      let testGroupList = /**@type {string}*/ ''
      selectedItems.selectedTestGroupColor = getComputedStyle(target).getPropertyValue('background-color')
      selectedItems.testResults = target
      target.classList.add("selected")
      for (let i = 0; i < testResults.length; i++) {
        const testResult = /**@type {TestGroupData}*/ testResults[i]
        const testPassed = /**@type {boolean}*/ testResult.Passed
        const testSkipped = /**@type {boolean}*/ testResult.Skipped
        const testPassedStatus = /**@type {string}*/ (testPassed) ? '' : (testSkipped ? 'skipped' : 'failed')
        const testId = /**@type {string}*/ target.attributes['id'].value
        testGroupList += `<div class="testGroupRow ${testPassedStatus}" data-groupid="${testId}" data-index="${i}">
        <span class="testStatus ${testPassedStatus}">${(testPassed) ? '&check' : (testSkipped ? '&dash' : '&cross')};</span>
        <span class="testTitle">${testResult.TestName}</span>
        <span class="testDuration"><span>${testResult.ElapsedTime}s </span>⏱</span>
      </div>`
      }
      const testGroupListElem = elements.testGroupListElem
      testGroupListElem.innerHTML = ''
      testGroupListElem.innerHTML = testGroupList

      if (shiftKey) {
        testGroupListElem.querySelectorAll('.testGroupRow')
                         .forEach((elem) => testGroupListHandler(elem, data))
      } else if (testResults.length === 1) {
        testGroupListHandler(testGroupListElem.querySelector('.testGroupRow'), data)
      }
    },

    /**
     *
     * @param {Element} target
     * @param {TestResults} data
     */
    testGroupListHandler: function (target, data) {
      const attribs = target['attributes']
      if (attribs.hasOwnProperty('data-groupid')) {
        const groupId = /**@type {number}*/ attribs['data-groupid'].value
        const testIndex = /**@type {number}*/ attribs['data-index'].value
        const testStatus = /**@type {TestStatus}*/ data[groupId]['TestResults'][testIndex]
        const testOutputDiv = /**@type {HTMLDivElement}*/ target.querySelector('div.testOutput')

        if (testOutputDiv == null) {
          const testOutputDiv = document.createElement('div')
          testOutputDiv.classList.add('testOutput')
          const consolePre = document.createElement('pre')
          consolePre.classList.add('console')
          const testDetailDiv = document.createElement('div')
          testDetailDiv.classList.add('testDetail')
          const packageNameDiv = document.createElement('div')
          packageNameDiv.classList.add('package')
          packageNameDiv.innerHTML = `<strong>Package:</strong> ${testStatus.Package}`
          const testFileNameDiv = document.createElement('div')
          testFileNameDiv.classList.add('filename')
          if (testStatus.TestFileName.trim() === "") {
            testFileNameDiv.innerHTML = `<strong>Filename:</strong> n/a &nbsp;&nbsp;`
          } else {
            testFileNameDiv.innerHTML = `<strong>Filename:</strong> ${testStatus.TestFileName} &nbsp;&nbsp;`
            testFileNameDiv.innerHTML += `<strong>Line:</strong> ${testStatus.TestFunctionDetail.Line} `
            testFileNameDiv.innerHTML += `<strong>Col:</strong> ${testStatus.TestFunctionDetail.Col}`
          }
          testDetailDiv.insertAdjacentElement('beforeend', packageNameDiv)
          testDetailDiv.insertAdjacentElement('beforeend', testFileNameDiv)
          testOutputDiv.insertAdjacentElement('afterbegin', consolePre)
          testOutputDiv.insertAdjacentElement('beforeend', testDetailDiv)
          target.insertAdjacentElement('beforeend', testOutputDiv)

          if (testStatus.Passed) {
            consolePre.classList.remove('skipped')
            consolePre.classList.remove('failed')
          } else if (testStatus.Skipped) {
            consolePre.classList.add('skipped')
            consolePre.classList.remove('failed')
          } else {
            consolePre.classList.remove('skipped')
            consolePre.classList.add('failed')
          }
          consolePre.textContent = testStatus.Output.join('')
        } else {
          testOutputDiv.remove()
        }
      }
    }
  }

  //+------------------------+
  //|    setup DOM events    |
  //+------------------------+
  elements.testResultsElem
          .addEventListener('click', event =>
            goTestReport.testResultsClickHandler(/**@type {HTMLElement}*/ addEventData(event).data.target,
                                                 event.shiftKey,
                                                 elements.data,
                                                 selectedItems,
                                                 goTestReport.testGroupListHandler))

  elements.testGroupListElem
          .addEventListener('click', event =>
            goTestReport.testGroupListHandler(/**@type {Element}*/ event.target,
                                              elements.data))

  return goTestReport
}


    

    const data = [{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":121.16,"Output":["",""],"Passed":false,"Skipped":false,"TestFileName":"0_s3mgrt_migrate_test.go","TestFunctionDetail":{"Line":14,"Col":1}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_access_and_secret_key_invalid","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_test.go:209: Test case [Should fail when access and secret key invalid] scheduled at [07-17-2024 17:59:46] \n","    system_test_framework.go:149: Test case [Should fail when access and secret key invalid] start at [07-17-2024 17:59:46] \n","2024/07/17 17:59:46 Creating wallet for Test0S3Migration-Should_fail_when_access_and_secret_key_invalid with walletIdx 529\n","File ./config/Test0S3Migration-Should_fail_when_access_and_secret_key_invalid_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:59:56.786641 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:59:56.786725 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:59:56.788054 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:211\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_access_and_secret_key_invalid\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:209: Test case [Should fail when access and secret key invalid] exit at [07-17-2024 17:59:56]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_access_and_secret_key_missing","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_test.go:228: Test case [Should fail when access and secret key missing] scheduled at [07-17-2024 17:59:56] \n","    system_test_framework.go:149: Test case [Should fail when access and secret key missing] start at [07-17-2024 17:59:56] \n","2024/07/17 17:59:56 Creating wallet for Test0S3Migration-Should_fail_when_access_and_secret_key_missing with walletIdx 530\n","File ./config/Test0S3Migration-Should_fail_when_access_and_secret_key_missing_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 18:00:06.888550 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 18:00:06.888654 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 18:00:06.890378 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:230\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_access_and_secret_key_missing\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:228: Test case [Should fail when access and secret key missing] exit at [07-17-2024 18:00:06]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_access_key_invalid","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_test.go:135: Test case [Should fail when access key invalid] scheduled at [07-17-2024 17:59:06] \n","    system_test_framework.go:149: Test case [Should fail when access key invalid] start at [07-17-2024 17:59:06] \n","2024/07/17 17:59:06 Creating wallet for Test0S3Migration-Should_fail_when_access_key_invalid with walletIdx 525\n","File ./config/Test0S3Migration-Should_fail_when_access_key_invalid_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:59:16.409837 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:59:16.409930 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:59:16.411013 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:137\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_access_key_invalid\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:135: Test case [Should fail when access key invalid] exit at [07-17-2024 17:59:16]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_access_key_missing","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_test.go:154: Test case [Should fail when access key missing] scheduled at [07-17-2024 17:59:16] \n","    system_test_framework.go:149: Test case [Should fail when access key missing] start at [07-17-2024 17:59:16] \n","2024/07/17 17:59:16 Creating wallet for Test0S3Migration-Should_fail_when_access_key_missing with walletIdx 526\n","File ./config/Test0S3Migration-Should_fail_when_access_key_missing_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:59:26.502670 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:59:26.502733 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:59:26.504005 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:156\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_access_key_missing\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:154: Test case [Should fail when access key missing] exit at [07-17-2024 17:59:26]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_allocation_flag_missing","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_test.go:117: Test case [Should fail when allocation flag missing] scheduled at [07-17-2024 17:58:56] \n","    system_test_framework.go:149: Test case [Should fail when allocation flag missing] start at [07-17-2024 17:58:56] \n","2024/07/17 17:58:56 Creating wallet for Test0S3Migration-Should_fail_when_allocation_flag_missing with walletIdx 524\n","File ./config/Test0S3Migration-Should_fail_when_allocation_flag_missing_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:59:06.318588 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:59:06.319027 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:59:06.320593 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:119\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_allocation_flag_missing\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:117: Test case [Should fail when allocation flag missing] exit at [07-17-2024 17:59:06]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_bucket_does_not_exist","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_test.go:80: Test case [Should fail when bucket does not exist] scheduled at [07-17-2024 17:58:36] \n","    system_test_framework.go:149: Test case [Should fail when bucket does not exist] start at [07-17-2024 17:58:36] \n","2024/07/17 17:58:36 Creating wallet for Test0S3Migration-Should_fail_when_bucket_does_not_exist with walletIdx 522\n","File ./config/Test0S3Migration-Should_fail_when_bucket_does_not_exist_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:58:46.126742 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:58:46.126921 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:58:46.128228 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:82\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_bucket_does_not_exist\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:80: Test case [Should fail when bucket does not exist] exit at [07-17-2024 17:58:46]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_bucket_flag_missing","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_test.go:99: Test case [Should fail when bucket flag missing] scheduled at [07-17-2024 17:58:46] \n","    system_test_framework.go:149: Test case [Should fail when bucket flag missing] start at [07-17-2024 17:58:46] \n","2024/07/17 17:58:46 Creating wallet for Test0S3Migration-Should_fail_when_bucket_flag_missing with walletIdx 523\n","File ./config/Test0S3Migration-Should_fail_when_bucket_flag_missing_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:58:56.230148 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:58:56.230281 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:58:56.232079 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:101\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_bucket_flag_missing\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:99: Test case [Should fail when bucket flag missing] exit at [07-17-2024 17:58:56]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_bucket_too_large_for_allocation","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_test.go:61: Test case [Should fail when bucket too large for allocation] scheduled at [07-17-2024 17:58:25] \n","    system_test_framework.go:149: Test case [Should fail when bucket too large for allocation] start at [07-17-2024 17:58:25] \n","2024/07/17 17:58:25 Creating wallet for Test0S3Migration-Should_fail_when_bucket_too_large_for_allocation with walletIdx 521\n","File ./config/Test0S3Migration-Should_fail_when_bucket_too_large_for_allocation_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:58:36.027207 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:58:36.027268 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:58:36.028768 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:63\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_bucket_too_large_for_allocation\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:61: Test case [Should fail when bucket too large for allocation] exit at [07-17-2024 17:58:36]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_secret_key_invalid","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_test.go:172: Test case [Should fail when secret key invalid] scheduled at [07-17-2024 17:59:26] \n","    system_test_framework.go:149: Test case [Should fail when secret key invalid] start at [07-17-2024 17:59:26] \n","2024/07/17 17:59:26 Creating wallet for Test0S3Migration-Should_fail_when_secret_key_invalid with walletIdx 527\n","File ./config/Test0S3Migration-Should_fail_when_secret_key_invalid_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:59:36.595617 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:59:36.595712 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:59:36.597260 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:174\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_secret_key_invalid\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:172: Test case [Should fail when secret key invalid] exit at [07-17-2024 17:59:36]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_fail_when_secret_key_missing","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_test.go:191: Test case [Should fail when secret key missing] scheduled at [07-17-2024 17:59:36] \n","    system_test_framework.go:149: Test case [Should fail when secret key missing] start at [07-17-2024 17:59:36] \n","2024/07/17 17:59:36 Creating wallet for Test0S3Migration-Should_fail_when_secret_key_missing with walletIdx 528\n","File ./config/Test0S3Migration-Should_fail_when_secret_key_missing_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:59:46.693813 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:59:46.693904 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:59:46.695295 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:193\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_fail_when_secret_key_missing\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:191: Test case [Should fail when secret key missing] exit at [07-17-2024 17:59:46]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_migrate_empty_bucket_successfully","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_test.go:42: Test case [Should migrate empty bucket successfully] scheduled at [07-17-2024 17:58:15] \n","    system_test_framework.go:149: Test case [Should migrate empty bucket successfully] start at [07-17-2024 17:58:15] \n","2024/07/17 17:58:15 Creating wallet for Test0S3Migration-Should_migrate_empty_bucket_successfully with walletIdx 520\n","File ./config/Test0S3Migration-Should_migrate_empty_bucket_successfully_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:58:25.924883 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:58:25.924980 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:58:25.926614 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:44\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_migrate_empty_bucket_successfully\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:42: Test case [Should migrate empty bucket successfully] exit at [07-17-2024 17:58:25]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3Migration/Should_migrate_existing_bucket_successfully","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_test.go:23: Test case [Should migrate existing bucket successfully] scheduled at [07-17-2024 17:58:05] \n","    system_test_framework.go:149: Test case [Should migrate existing bucket successfully] start at [07-17-2024 17:58:05] \n","2024/07/17 17:58:05 Creating wallet for Test0S3Migration-Should_migrate_existing_bucket_successfully with walletIdx 519\n","File ./config/Test0S3Migration-Should_migrate_existing_bucket_successfully_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:58:15.823228 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:58:15.823319 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:58:15.824642 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_test.go:25\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3Migration/Should_migrate_existing_bucket_successfully\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_test.go:23: Test case [Should migrate existing bucket successfully] exit at [07-17-2024 17:58:15]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":91.07,"Output":["","    system_test_framework.go:70: Test setup [Setup s3 bucket with relevant file] scheduled at [07-17-2024 17:56:34] \n","    system_test_framework.go:80: Test setup [Setup s3 bucket with relevant file] start at [07-17-2024 17:56:34] \n","    system_test_framework.go:93: Test setup [Setup s3 bucket with relevant file] exit at [07-17-2024 17:56:34]\n",""],"Passed":false,"Skipped":false,"TestFileName":"0_s3mgrt_migrate_alternate_test.go","TestFunctionDetail":{"Line":32,"Col":1}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate/Should_error_out_if_workdir_is_not_default_and_not_empty","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_alternate_test.go:294: Test case [Should error out if workdir is not default and not empty] scheduled at [07-17-2024 17:57:55] \n","    system_test_framework.go:149: Test case [Should error out if workdir is not default and not empty] start at [07-17-2024 17:57:55] \n","2024/07/17 17:57:55 Creating wallet for Test0S3MigrationAlternate-Should_error_out_if_workdir_is_not_default_and_not_empty with walletIdx 518\n","File ./config/Test0S3MigrationAlternate-Should_error_out_if_workdir_is_not_default_and_not_empty_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:58:05.725564 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:58:05.725885 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:58:05.727270 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate_test.go:296\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternate/Should_error_out_if_workdir_is_not_default_and_not_empty\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate_test.go:294: Test case [Should error out if workdir is not default and not empty] exit at [07-17-2024 17:58:05]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate/Should_migrate_as_copy_bucket_successfully","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.07,"Output":["","    0_s3mgrt_migrate_alternate_test.go:115: Test case [Should migrate as copy bucket successfully] scheduled at [07-17-2024 17:56:55] \n","    system_test_framework.go:149: Test case [Should migrate as copy bucket successfully] start at [07-17-2024 17:56:55] \n","2024/07/17 17:56:55 Creating wallet for Test0S3MigrationAlternate-Should_migrate_as_copy_bucket_successfully with walletIdx 512\n","File ./config/Test0S3MigrationAlternate-Should_migrate_as_copy_bucket_successfully_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:57:05.156786 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:57:05.156874 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:57:05.158334 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate_test.go:117\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternate/Should_migrate_as_copy_bucket_successfully\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate_test.go:115: Test case [Should migrate as copy bucket successfully] exit at [07-17-2024 17:57:05]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate/Should_migrate_existing_bucket_successfully_with_encryption_on","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_alternate_test.go:156: Test case [Should migrate existing bucket successfully with encryption on] scheduled at [07-17-2024 17:57:05] \n","    system_test_framework.go:149: Test case [Should migrate existing bucket successfully with encryption on] start at [07-17-2024 17:57:05] \n","2024/07/17 17:57:05 Creating wallet for Test0S3MigrationAlternate-Should_migrate_existing_bucket_successfully_with_encryption_on with walletIdx 513\n","File ./config/Test0S3MigrationAlternate-Should_migrate_existing_bucket_successfully_with_encryption_on_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:57:15.246723 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:57:15.246948 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:57:15.248412 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate_test.go:158\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternate/Should_migrate_existing_bucket_successfully_with_encryption_on\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate_test.go:156: Test case [Should migrate existing bucket successfully with encryption on] exit at [07-17-2024 17:57:15]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate/Should_migrate_existing_bucket_successfully_with_skip_0_and_replace_existing_file","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_alternate_test.go:60: Test case [Should migrate existing bucket successfully with skip 0 and replace existing file] scheduled at [07-17-2024 17:56:34] \n","    system_test_framework.go:149: Test case [Should migrate existing bucket successfully with skip 0 and replace existing file] start at [07-17-2024 17:56:34] \n","2024/07/17 17:56:34 Creating wallet for Test0S3MigrationAlternate-Should_migrate_existing_bucket_successfully_with_skip_0_and_replace_existing_file with walletIdx 510\n","File ./config/Test0S3MigrationAlternate-Should_migrate_existing_bucket_successfully_with_skip_0_and_replace_existing_file_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:56:45.000252 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:56:45.000424 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:56:45.003805 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate_test.go:62\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternate/Should_migrate_existing_bucket_successfully_with_skip_0_and_replace_existing_file\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate_test.go:60: Test case [Should migrate existing bucket successfully with skip 0 and replace existing file] exit at [07-17-2024 17:56:45]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate/Should_migrate_existing_bucket_to_specified_path_successfully_with_encryption_on","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.08,"Output":["","    0_s3mgrt_migrate_alternate_test.go:87: Test case [Should migrate existing bucket to specified path successfully with encryption on] scheduled at [07-17-2024 17:56:45] \n","    system_test_framework.go:149: Test case [Should migrate existing bucket to specified path successfully with encryption on] start at [07-17-2024 17:56:45] \n","2024/07/17 17:56:45 Creating wallet for Test0S3MigrationAlternate-Should_migrate_existing_bucket_to_specified_path_successfully_with_encryption_on with walletIdx 511\n","File ./config/Test0S3MigrationAlternate-Should_migrate_existing_bucket_to_specified_path_successfully_with_encryption_on_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:56:55.087709 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:56:55.087777 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:56:55.089020 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate_test.go:89\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternate/Should_migrate_existing_bucket_to_specified_path_successfully_with_encryption_on\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate_test.go:87: Test case [Should migrate existing bucket to specified path successfully with encryption on] exit at [07-17-2024 17:56:55]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate/Should_migrate_successfully_and_delete_the_s3_bucket_file_and_use_custom_workdir","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_alternate_test.go:261: Test case [Should migrate successfully and delete the s3 bucket file and use custom workdir] scheduled at [07-17-2024 17:57:45] \n","    system_test_framework.go:149: Test case [Should migrate successfully and delete the s3 bucket file and use custom workdir] start at [07-17-2024 17:57:45] \n","2024/07/17 17:57:45 Creating wallet for Test0S3MigrationAlternate-Should_migrate_successfully_and_delete_the_s3_bucket_file_and_use_custom_workdir with walletIdx 517\n","File ./config/Test0S3MigrationAlternate-Should_migrate_successfully_and_delete_the_s3_bucket_file_and_use_custom_workdir_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:57:55.628262 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:57:55.628344 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:57:55.629746 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate_test.go:263\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternate/Should_migrate_successfully_and_delete_the_s3_bucket_file_and_use_custom_workdir\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate_test.go:261: Test case [Should migrate successfully and delete the s3 bucket file and use custom workdir] exit at [07-17-2024 17:57:55]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate/Should_migrate_successfully_with_duplicate_files_with_skip_flag_==_2","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_alternate_test.go:202: Test case [Should migrate successfully with duplicate files with skip flag == 2] scheduled at [07-17-2024 17:57:25] \n","    system_test_framework.go:149: Test case [Should migrate successfully with duplicate files with skip flag == 2] start at [07-17-2024 17:57:25] \n","2024/07/17 17:57:25 Creating wallet for Test0S3MigrationAlternate-Should_migrate_successfully_with_duplicate_files_with_skip_flag_==_2 with walletIdx 515\n","File ./config/Test0S3MigrationAlternate-Should_migrate_successfully_with_duplicate_files_with_skip_flag_==_2_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:57:35.441175 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:57:35.441271 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:57:35.442723 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate_test.go:204\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternate/Should_migrate_successfully_with_duplicate_files_with_skip_flag_==_2\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate_test.go:202: Test case [Should migrate successfully with duplicate files with skip flag == 2] exit at [07-17-2024 17:57:35]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate/Should_migrate_successfully_with_duplication_files__with_skip_flag_==_2_and_dup-suffix","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_alternate_test.go:231: Test case [Should migrate successfully with duplication files  with skip flag == 2 and dup-suffix] scheduled at [07-17-2024 17:57:35] \n","    system_test_framework.go:149: Test case [Should migrate successfully with duplication files  with skip flag == 2 and dup-suffix] start at [07-17-2024 17:57:35] \n","2024/07/17 17:57:35 Creating wallet for Test0S3MigrationAlternate-Should_migrate_successfully_with_duplication_files__with_skip_flag_==_2_and_dup-suffix with walletIdx 516\n","File ./config/Test0S3MigrationAlternate-Should_migrate_successfully_with_duplication_files__with_skip_flag_==_2_and_dup-suffix_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:57:45.530817 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:57:45.530899 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:57:45.532317 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate_test.go:233\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternate/Should_migrate_successfully_with_duplication_files__with_skip_flag_==_2_and_dup-suffix\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate_test.go:231: Test case [Should migrate successfully with duplication files  with skip flag == 2 and dup-suffix] exit at [07-17-2024 17:57:45]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternate/Should_skip_migration_with_skip_flag_==_1_and_migartion_should_be_skipped","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_alternate_test.go:182: Test case [Should skip migration with skip flag == 1 and migartion should be skipped] scheduled at [07-17-2024 17:57:15] \n","    system_test_framework.go:149: Test case [Should skip migration with skip flag == 1 and migartion should be skipped] start at [07-17-2024 17:57:15] \n","2024/07/17 17:57:15 Creating wallet for Test0S3MigrationAlternate-Should_skip_migration_with_skip_flag_==_1_and_migartion_should_be_skipped with walletIdx 514\n","File ./config/Test0S3MigrationAlternate-Should_skip_migration_with_skip_flag_==_1_and_migartion_should_be_skipped_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:57:25.344465 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:57:25.344597 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:57:25.346009 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate_test.go:184\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternate/Should_skip_migration_with_skip_flag_==_1_and_migartion_should_be_skipped\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate_test.go:182: Test case [Should skip migration with skip flag == 1 and migartion should be skipped] exit at [07-17-2024 17:57:25]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":91.87,"Output":["","    system_test_framework.go:70: Test setup [Setup s3 bucket with relevant file] scheduled at [07-17-2024 17:55:02] \n","    system_test_framework.go:80: Test setup [Setup s3 bucket with relevant file] start at [07-17-2024 17:55:02] \n","    system_test_framework.go:93: Test setup [Setup s3 bucket with relevant file] exit at [07-17-2024 17:55:03]\n",""],"Passed":false,"Skipped":false,"TestFileName":"0_s3mgrt_migrate_alternate2_test.go","TestFunctionDetail":{"Line":22,"Col":1}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2/Should_migrate_existing_bucket_successfully_with_concurrency==4_and_working_dir_current_dir","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.08,"Output":["","    0_s3mgrt_migrate_alternate2_test.go:50: Test case [Should migrate existing bucket successfully with concurrency==4 and working dir current dir] scheduled at [07-17-2024 17:55:03] \n","    system_test_framework.go:149: Test case [Should migrate existing bucket successfully with concurrency==4 and working dir current dir] start at [07-17-2024 17:55:03] \n","2024/07/17 17:55:03 Creating wallet for Test0S3MigrationAlternatePart2-Should_migrate_existing_bucket_successfully_with_concurrency==4_and_working_dir_current_dir with walletIdx 501\n","File ./config/Test0S3MigrationAlternatePart2-Should_migrate_existing_bucket_successfully_with_concurrency==4_and_working_dir_current_dir_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:55:13.387930 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:55:13.387977 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:55:13.389093 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate2_test.go:52\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternatePart2/Should_migrate_existing_bucket_successfully_with_concurrency==4_and_working_dir_current_dir\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate2_test.go:50: Test case [Should migrate existing bucket successfully with concurrency==4 and working dir current dir] exit at [07-17-2024 17:55:13]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2/Should_migrate_existing_bucket_successfully_with_files_staring_with_given_prefix","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_alternate2_test.go:153: Test case [Should migrate existing bucket successfully with files staring with given prefix] scheduled at [07-17-2024 17:55:33] \n","    system_test_framework.go:149: Test case [Should migrate existing bucket successfully with files staring with given prefix] start at [07-17-2024 17:55:33] \n","2024/07/17 17:55:33 Creating wallet for Test0S3MigrationAlternatePart2-Should_migrate_existing_bucket_successfully_with_files_staring_with_given_prefix with walletIdx 504\n","File ./config/Test0S3MigrationAlternatePart2-Should_migrate_existing_bucket_successfully_with_files_staring_with_given_prefix_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:55:43.691211 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:55:43.691302 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:55:43.692580 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate2_test.go:155\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternatePart2/Should_migrate_existing_bucket_successfully_with_files_staring_with_given_prefix\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate2_test.go:153: Test case [Should migrate existing bucket successfully with files staring with given prefix] exit at [07-17-2024 17:55:43]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2/Should_migrate_existing_bucket_successfully_with_newer_than_prefix","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.12,"Output":["","    0_s3mgrt_migrate_alternate2_test.go:82: Test case [Should migrate existing bucket successfully with newer than prefix] scheduled at [07-17-2024 17:55:13] \n","    system_test_framework.go:149: Test case [Should migrate existing bucket successfully with newer than prefix] start at [07-17-2024 17:55:13] \n","2024/07/17 17:55:13 Creating wallet for Test0S3MigrationAlternatePart2-Should_migrate_existing_bucket_successfully_with_newer_than_prefix with walletIdx 502\n","File ./config/Test0S3MigrationAlternatePart2-Should_migrate_existing_bucket_successfully_with_newer_than_prefix_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:55:23.503447 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:55:23.503534 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:55:23.505177 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate2_test.go:84\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternatePart2/Should_migrate_existing_bucket_successfully_with_newer_than_prefix\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate2_test.go:82: Test case [Should migrate existing bucket successfully with newer than prefix] exit at [07-17-2024 17:55:23]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2/Should_migrate_existing_bucket_successfully_with_older_than_prefix","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_alternate2_test.go:116: Test case [Should migrate existing bucket successfully with older than prefix] scheduled at [07-17-2024 17:55:23] \n","    system_test_framework.go:149: Test case [Should migrate existing bucket successfully with older than prefix] start at [07-17-2024 17:55:23] \n","2024/07/17 17:55:23 Creating wallet for Test0S3MigrationAlternatePart2-Should_migrate_existing_bucket_successfully_with_older_than_prefix with walletIdx 503\n","File ./config/Test0S3MigrationAlternatePart2-Should_migrate_existing_bucket_successfully_with_older_than_prefix_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:55:33.597926 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:55:33.598160 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:55:33.599536 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate2_test.go:118\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternatePart2/Should_migrate_existing_bucket_successfully_with_older_than_prefix\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate2_test.go:116: Test case [Should migrate existing bucket successfully with older than prefix] exit at [07-17-2024 17:55:33]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2/Should_pass_concurrency_flag_is_set_to_20","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.07,"Output":["","    0_s3mgrt_migrate_alternate2_test.go:285: Test case [Should pass concurrency flag is set to 20] scheduled at [07-17-2024 17:56:03] \n","    system_test_framework.go:149: Test case [Should pass concurrency flag is set to 20] start at [07-17-2024 17:56:03] \n","2024/07/17 17:56:03 Creating wallet for Test0S3MigrationAlternatePart2-Should_pass_concurrency_flag_is_set_to_20 with walletIdx 507\n","File ./config/Test0S3MigrationAlternatePart2-Should_pass_concurrency_flag_is_set_to_20_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:56:13.941430 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:56:13.941475 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:56:13.942486 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate2_test.go:287\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternatePart2/Should_pass_concurrency_flag_is_set_to_20\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate2_test.go:285: Test case [Should pass concurrency flag is set to 20] exit at [07-17-2024 17:56:13]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2/Should_pass_retry_flag_is_set_to_4","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.1,"Output":["","    0_s3mgrt_migrate_alternate2_test.go:320: Test case [Should pass retry flag is set to 4] scheduled at [07-17-2024 17:56:13] \n","    system_test_framework.go:149: Test case [Should pass retry flag is set to 4] start at [07-17-2024 17:56:13] \n","2024/07/17 17:56:13 Creating wallet for Test0S3MigrationAlternatePart2-Should_pass_retry_flag_is_set_to_4 with walletIdx 508\n","File ./config/Test0S3MigrationAlternatePart2-Should_pass_retry_flag_is_set_to_4_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:56:24.043918 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:56:24.043995 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:56:24.045074 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate2_test.go:322\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternatePart2/Should_pass_retry_flag_is_set_to_4\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate2_test.go:320: Test case [Should pass retry flag is set to 4] exit at [07-17-2024 17:56:24]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2/Should_pass_when_access_key_and_secret_key_is_missing_but_aws-cred-path_path_is_given","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.08,"Output":["","    0_s3mgrt_migrate_alternate2_test.go:237: Test case [Should pass when access key and secret key is missing but aws-cred-path path is given] scheduled at [07-17-2024 17:55:53] \n","    system_test_framework.go:149: Test case [Should pass when access key and secret key is missing but aws-cred-path path is given] start at [07-17-2024 17:55:53] \n","2024/07/17 17:55:53 Creating wallet for Test0S3MigrationAlternatePart2-Should_pass_when_access_key_and_secret_key_is_missing_but_aws-cred-path_path_is_given with walletIdx 506\n","File ./config/Test0S3MigrationAlternatePart2-Should_pass_when_access_key_and_secret_key_is_missing_but_aws-cred-path_path_is_given_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:56:03.866388 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:56:03.866467 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:56:03.867711 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate2_test.go:239\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternatePart2/Should_pass_when_access_key_and_secret_key_is_missing_but_aws-cred-path_path_is_given\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate2_test.go:237: Test case [Should pass when access key and secret key is missing but aws-cred-path path is given] exit at [07-17-2024 17:56:03]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2/Should_pass_when_allocation_flag_missing_but_allocation_path_is_given","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.09,"Output":["","    0_s3mgrt_migrate_alternate2_test.go:197: Test case [Should pass when allocation flag missing but allocation path is given] scheduled at [07-17-2024 17:55:43] \n","    system_test_framework.go:149: Test case [Should pass when allocation flag missing but allocation path is given] start at [07-17-2024 17:55:43] \n","2024/07/17 17:55:43 Creating wallet for Test0S3MigrationAlternatePart2-Should_pass_when_allocation_flag_missing_but_allocation_path_is_given with walletIdx 505\n","File ./config/Test0S3MigrationAlternatePart2-Should_pass_when_allocation_flag_missing_but_allocation_path_is_given_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:55:53.783108 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:55:53.783200 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:55:53.784839 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate2_test.go:199\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternatePart2/Should_pass_when_allocation_flag_missing_but_allocation_path_is_given\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate2_test.go:197: Test case [Should pass when allocation flag missing but allocation path is given] exit at [07-17-2024 17:55:53]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"Test0S3MigrationAlternatePart2/Should_pass_when_filename_size_is_more_than_100_character_with_renamed_file_names","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.61,"Output":["","    0_s3mgrt_migrate_alternate2_test.go:355: Test case [Should pass when filename size is more than 100 character with renamed file names] scheduled at [07-17-2024 17:56:24] \n","    system_test_framework.go:149: Test case [Should pass when filename size is more than 100 character with renamed file names] start at [07-17-2024 17:56:24] \n","2024/07/17 17:56:24 Creating wallet for Test0S3MigrationAlternatePart2-Should_pass_when_filename_size_is_more_than_100_character_with_renamed_file_names with walletIdx 509\n","File ./config/Test0S3MigrationAlternatePart2-Should_pass_when_filename_size_is_more_than_100_character_with_renamed_file_names_wallet.json written successfully.\n","    zboxcli_create_allocation_test.go:444: Creating new allocation...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused -\u003cNEWLINE\u003e- Error initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2024/07/17 17:56:34.651573 wallet_base.go:331: ******* Wallet SDK Version:v1.15.1-17-g1364fe53 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk        [INFO]   2024/07/17 17:56:34.651667 sdk.go:103: ******* Storage SDK Version: v1.15.1-17-g1364fe53 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2024/07/17 17:56:34.653088 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    utils.go:105: \u001b[31mError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:817\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:799\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/tests/cli_tests/0_s3mgrt_migrate_alternate2_test.go:363\n","        \t            \t\t\t\t/root/actions-runner5/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/root/actions-runner5/_work/_tool/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/asm_amd64.s:1695\n","        \tError:      \tReceived unexpected error:\n","        \t            \texit status 1\n","        \tTest:       \tTest0S3MigrationAlternatePart2/Should_pass_when_filename_size_is_more_than_100_character_with_renamed_file_names\n","        \tMessages:   \tcreate new allocation failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused\n","        \t            \tError initializing core SDK. get_network_details_error: Unable to get http request with error Get \"https://dev-5.devnet-0chain.net/dns/network\": dial tcp 65.21.10.156:443: connect: connection refused)\n","    0_s3mgrt_migrate_alternate2_test.go:355: Test case [Should pass when filename size is more than 100 character with renamed file names] exit at [07-17-2024 17:56:34]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]}]

    const report = window.GoTestReport({
                                         data: data,
                                         testResultsElem: document.getElementById('testResults'),
                                         testGroupListElem: document.getElementById('testGroupList')
                                       });


</script>
</body>
</html>
