<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>0Chain System test suite: Challenge tests [fix_challenge-based-on-weight/34a3fcaf] ran against [dev-7.devnet-0chain.net] at [2023-10-18_11.44.14]</title>
    <style type="text/css">
        body {
            font-family: sans-serif;
            background-color: #f3f3f3;
            border-top: 2px #dee6e8 solid;
            margin: 0;
        }

        div.pageHeader span.projectTitle {
            font-family: serif;
            font-size: 2em;
            padding-left: 56px;
            padding-top: 80px;
            display: block;
            color: #a5a5a5;
            text-shadow: 0 -1px 1px white;
        }

        div.pageHeader div.testStats {
            position: absolute;
            top: 7px;
            right: 52px;
            font-size: 0.8em;
            color: #a2a2a2;
        }

        div.pageHeader div.testStats span.indicator {
            font-size: 2em;
            position: relative;
            top: 5px;
            text-shadow: 0 1px 0 white;
        }

        div.pageHeader div.testStats span strong {
            margin-right: 16px;
        }

        div.pageHeader div.testStats span.total {
            border-right: 1px #afafaf dotted;
            background: #8298af;
        }

        div.pageHeader div.testStats span.passed {
            border-right: 1px #afafaf dotted;
            background: #6fca83;
        }

        div.pageHeader div.testStats span.skipped {
            background: #bababa;
        }

        div.pageHeader div.testStats span.failed {
            background: #ff7676;
        }

        div.pageHeader div.testStats span {
            margin-right: 1px;
            height: 55px;
            padding: 20px 8px 18px;
            color: white;
        }

        div.pageHeader .testGroupsTitle {
            margin: 16px 32px 8px 40px;
            font-size: 0.9em;
            color: darkgrey;
            display: inline-block;
        }

        div.pageHeader .testExecutionDate {
            display: inline-block;
            position: absolute;
            right: 10px;
            margin: 14px 32px 8px 40px;
            color: #9e9e9e;
            font-size: 0.9em;
        }

        .testReportContainer {
            padding: 0 32px 32px 32px;
        }

        .cardContainer {
            padding: 16px 16px 16px;
            box-shadow: 0 4px 4px #d4d4d4;
            background-color: white;
        }

        #testResults {
            display: flex;
            flex-wrap: wrap;
        }

        .testResultGroup {
            width: 24px;
            height: 24px;
            background-color: #43c143;
            margin-left: 1px;
            margin-bottom: 1px;
            box-sizing: border-box;
        }

        .testResultGroup.selected {
            border: 1px white solid;
            background-color: black !important;
        }

        .testResultGroup.skipped {
            border: 2px gray solid;
        }

        .testResultGroup.failed {
            background-color: red;
        }

        .cardContainer.testGroupList,
        .cardContainer.testDetail {
            margin-top: 16px;
            padding: 16px;
        }

        .cardContainer.testGroupList {
            color: #9c9c9c;
            padding: 0;
        }

        .cardContainer.testGroupList .testGroupRow {
            cursor: default;
            border-bottom: 1px #dadada dotted;
        }

        .cardContainer.testGroupList .testGroupRow span.testStatus {
            font-size: 1.2em;
            font-weight: bold;
            color: #139e13;
            pointer-events: none;
            display: inline-block;
            overflow: hidden;
            float: left;
            padding-top: 10px;
            padding-left: 20px;
            padding-right: 12px;
        }

        .cardContainer.testGroupList .testGroupRow span.testStatus.skipped {
            color: gray;
        }

        .cardContainer.testGroupList .testGroupRow span.testStatus.failed {
            color: red;
        }

        .cardContainer.testGroupList .testGroupRow span.testTitle {
            font-size: 0.9em;
            padding: 12px 0 10px;
            display: inline-block;
            pointer-events: none;
            color: #525252;
            text-overflow: ellipsis;
            overflow: hidden;
            width: calc(100% - 110px);
        }

        .cardContainer.testGroupList .testGroupRow span.testDuration {
            pointer-events: none;
        }

        .cardContainer.testGroupList .testGroupRow {
            position: relative;
            border-left: 4px #43c143 solid;
        }

        .cardContainer.testGroupList .testGroupRow.skipped {
            color: gray;
            border-left: 4px gray solid;
        }

        .cardContainer.testGroupList .testGroupRow.failed {
            color: red;
            border-left: 4px red solid;
        }

        .cardContainer.testGroupList .testGroupRow:hover {
            background-color: #fffaea;
            transition: 0.250s;
        }

        .cardContainer .testOutput {
            padding: 8px 16px 24px 16px;
        }

        .cardContainer .console {
            display: block;
            font-family: monospace;
            padding: 10px;
            background-color: #424242;
            color: #1aff00;
            border-bottom: 1px #1aff00 dotted;
            overflow: auto;
            font-size: 1.1em;
        }

        .cardContainer .testOutput .testDetail {
            border-bottom: 1px #d0d0d0 solid;
            padding: 16px;
            background-color: #e6e6e6;
            border-radius: 0 0 4px 4px;
            color: dimgrey;
            font-size: 0.8em;
        }

        .cardContainer .console.skipped{
            color: #d9d9d9;
        }

        .cardContainer .console.failed {
            color: #ffb2b2;
        }

        .cardContainer .testDuration {
            position: absolute;
            top: 5px;
            right: 8px;
            text-align: right;
            padding-right: 8px;
            box-sizing: border-box;
        }
    </style>
</head>
<body>
<div class="pageHeader">
    <span class="projectTitle">0Chain System test suite: Challenge tests [fix_challenge-based-on-weight/34a3fcaf] ran against [dev-7.devnet-0chain.net] at [2023-10-18_11.44.14]</span>
    <div class="testStats">
        <span class="total"><span class="indicator">&boxbox;</span> Total: <strong>9</strong>Duration: <strong>3ms</strong>
        </span><span class="passed"><span class="indicator">&check;</span> Passed: <strong>0</strong>
        </span><span class="skipped"><span class="indicator">&dash;</span> Skipped: <strong>0</strong>
        </span><span class="failed"><span class="indicator">&cross;</span> Failed: <strong>9</strong>
        </span>
    </div>
    <span class="testGroupsTitle">Test Groups:</span>
    <span class="testExecutionDate">October 18, 2023 12:49:06</span>
</div>
<div class="testReportContainer">
    <div class="cardContainer">
        <div id="testResults">
            
                <div class="testResultGroup failed " id="0"></div>
            
                <div class="testResultGroup failed " id="1"></div>
            
                <div class="testResultGroup failed " id="2"></div>
            
                <div class="testResultGroup failed " id="3"></div>
            
                <div class="testResultGroup failed " id="4"></div>
            
                <div class="testResultGroup failed " id="5"></div>
            
                <div class="testResultGroup failed " id="6"></div>
            
                <div class="testResultGroup failed " id="7"></div>
            
                <div class="testResultGroup failed " id="8"></div>
            
        </div>
    </div>
    <div class="cardContainer testGroupList" id="testGroupList"></div>
</div>
<script type="application/javascript">
    /**
 * @typedef TestStatus
 * @property {string} TestName
 * @property {string} Package
 * @property {number} ElapsedTime
 * @property {Array.<string>} Output
 * @property {boolean} Passed
 * @property {boolean} Skipped
 */
class TestStatus {}

/**
 * @typedef TestGroupData
 * @type {object}
 * @property {string} FailureIndicator
 * @property {string} SkippedIndicator
 * @property {Array.<TestStatus>}
 */
class TestGroupData {}

/**
 * @typedef TestResults
 * @type {Array.<TestGroupData>}
 */
class TestResults extends Array {}

/**
 * @typedef SelectedItems
 * @property {HTMLElement|EventTarget} testResults
 * @property {String} selectedTestGroupColor
 */
class SelectedItems {}

/**
 * @typedef GoTestReportElements
 * @property {TestResults} data
 * @property {HTMLElement} testResultsElem
 * @property {HTMLElement} testGroupListElem
 */
class GoTestReportElements {}


/**
 * Main entry point for GoTestReport.
 * @param {GoTestReportElements} elements
 * @returns {{testResultsClickHandler: testResultsClickHandler}}
 * @constructor
 */
window.GoTestReport = function (elements) {
  const /**@type {SelectedItems}*/ selectedItems = {
    testResults: null,
    selectedTestGroupColor: null
  }

  function addEventData(event) {
    if (event.data == null) {
      event.data = {target: event.target}
    }
    return event
  }


  const goTestReport = {
    /**
     * Invoked when a user clicks on one of the test group div elements.
     * @param {HTMLElement} target The element associated with the test group.
     * @param {boolean} shiftKey If pressed, all of test detail associated to the test group is shown.
     * @param {TestResults} data
     * @param {SelectedItems} selectedItems
     * @param {function(target: Element, data: TestResults)} testGroupListHandler
     */
    testResultsClickHandler: function (target,
                                       shiftKey,
                                       data,
                                       selectedItems,
                                       testGroupListHandler) {

      if (target.classList.contains('testResultGroup') === false) {
        return
      }
      if (selectedItems.testResults != null) {
        let testResultsElement = /**@type {HTMLElement}*/ selectedItems.testResults
        testResultsElement.classList.remove("selected")
        testResultsElement.style.backgroundColor = selectedItems.selectedTestGroupColor
      }
      const testGroupId = /**@type {number}*/ target.id
      if ((target.id === undefined)
        || (data[testGroupId] === undefined)
        || (data[testGroupId]['TestResults'] === undefined)) {
        return
      }
      const testResults = /**@type {TestResults}*/ data[testGroupId]['TestResults']
      let testGroupList = /**@type {string}*/ ''
      selectedItems.selectedTestGroupColor = getComputedStyle(target).getPropertyValue('background-color')
      selectedItems.testResults = target
      target.classList.add("selected")
      for (let i = 0; i < testResults.length; i++) {
        const testResult = /**@type {TestGroupData}*/ testResults[i]
        const testPassed = /**@type {boolean}*/ testResult.Passed
        const testSkipped = /**@type {boolean}*/ testResult.Skipped
        const testPassedStatus = /**@type {string}*/ (testPassed) ? '' : (testSkipped ? 'skipped' : 'failed')
        const testId = /**@type {string}*/ target.attributes['id'].value
        testGroupList += `<div class="testGroupRow ${testPassedStatus}" data-groupid="${testId}" data-index="${i}">
        <span class="testStatus ${testPassedStatus}">${(testPassed) ? '&check' : (testSkipped ? '&dash' : '&cross')};</span>
        <span class="testTitle">${testResult.TestName}</span>
        <span class="testDuration"><span>${testResult.ElapsedTime}s </span>⏱</span>
      </div>`
      }
      const testGroupListElem = elements.testGroupListElem
      testGroupListElem.innerHTML = ''
      testGroupListElem.innerHTML = testGroupList

      if (shiftKey) {
        testGroupListElem.querySelectorAll('.testGroupRow')
                         .forEach((elem) => testGroupListHandler(elem, data))
      } else if (testResults.length === 1) {
        testGroupListHandler(testGroupListElem.querySelector('.testGroupRow'), data)
      }
    },

    /**
     *
     * @param {Element} target
     * @param {TestResults} data
     */
    testGroupListHandler: function (target, data) {
      const attribs = target['attributes']
      if (attribs.hasOwnProperty('data-groupid')) {
        const groupId = /**@type {number}*/ attribs['data-groupid'].value
        const testIndex = /**@type {number}*/ attribs['data-index'].value
        const testStatus = /**@type {TestStatus}*/ data[groupId]['TestResults'][testIndex]
        const testOutputDiv = /**@type {HTMLDivElement}*/ target.querySelector('div.testOutput')

        if (testOutputDiv == null) {
          const testOutputDiv = document.createElement('div')
          testOutputDiv.classList.add('testOutput')
          const consolePre = document.createElement('pre')
          consolePre.classList.add('console')
          const testDetailDiv = document.createElement('div')
          testDetailDiv.classList.add('testDetail')
          const packageNameDiv = document.createElement('div')
          packageNameDiv.classList.add('package')
          packageNameDiv.innerHTML = `<strong>Package:</strong> ${testStatus.Package}`
          const testFileNameDiv = document.createElement('div')
          testFileNameDiv.classList.add('filename')
          if (testStatus.TestFileName.trim() === "") {
            testFileNameDiv.innerHTML = `<strong>Filename:</strong> n/a &nbsp;&nbsp;`
          } else {
            testFileNameDiv.innerHTML = `<strong>Filename:</strong> ${testStatus.TestFileName} &nbsp;&nbsp;`
            testFileNameDiv.innerHTML += `<strong>Line:</strong> ${testStatus.TestFunctionDetail.Line} `
            testFileNameDiv.innerHTML += `<strong>Col:</strong> ${testStatus.TestFunctionDetail.Col}`
          }
          testDetailDiv.insertAdjacentElement('beforeend', packageNameDiv)
          testDetailDiv.insertAdjacentElement('beforeend', testFileNameDiv)
          testOutputDiv.insertAdjacentElement('afterbegin', consolePre)
          testOutputDiv.insertAdjacentElement('beforeend', testDetailDiv)
          target.insertAdjacentElement('beforeend', testOutputDiv)

          if (testStatus.Passed) {
            consolePre.classList.remove('skipped')
            consolePre.classList.remove('failed')
          } else if (testStatus.Skipped) {
            consolePre.classList.add('skipped')
            consolePre.classList.remove('failed')
          } else {
            consolePre.classList.remove('skipped')
            consolePre.classList.add('failed')
          }
          consolePre.textContent = testStatus.Output.join('')
        } else {
          testOutputDiv.remove()
        }
      }
    }
  }

  //+------------------------+
  //|    setup DOM events    |
  //+------------------------+
  elements.testResultsElem
          .addEventListener('click', event =>
            goTestReport.testResultsClickHandler(/**@type {HTMLElement}*/ addEventData(event).data.target,
                                                 event.shiftKey,
                                                 elements.data,
                                                 selectedItems,
                                                 goTestReport.testGroupListHandler))

  elements.testGroupListElem
          .addEventListener('click', event =>
            goTestReport.testGroupListHandler(/**@type {Element}*/ event.target,
                                              elements.data))

  return goTestReport
}


    

    const data = [{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"TestProtocolChallenge","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":3.18,"Output":["","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:45:40] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:45:40] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:45:50.632409 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:45:50.632552 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:45:50.656019 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc00012c5d0), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:45:50]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:46:02] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:46:02] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:46:12.182263 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:46:12.182326 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:46:12.205840 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc0008842b8), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:46:12]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:46:23] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:46:23] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:46:33.825881 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:46:33.825944 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:46:33.849341 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc00017c030), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:46:33]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:46:35] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:46:35] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:46:45.209760 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:46:45.209824 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:46:45.233958 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc00053a6c0), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:46:45]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:46:46] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:46:46] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:46:56.679255 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:46:56.679326 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:46:56.703312 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc0000126c0), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:46:56]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:46:58] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:46:58] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:47:08.279411 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:47:08.279478 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:47:08.302702 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc000930120), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:47:08]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:47:09] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:47:09] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:47:19.647834 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:47:19.647900 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:47:19.671409 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc000bd8060), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:47:19]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:47:20] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:47:20] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:47:31.004010 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:47:31.004198 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:47:31.028354 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc0004e41f8), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:47:31]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:47:32] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:47:32] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:47:42.352551 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:47:42.352613 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:47:42.377868 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc000b66498), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:47:42]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:47:43] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:47:43] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:47:53.828287 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:47:53.828345 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:47:53.850042 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc00061a4e0), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:47:53]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:48:05] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:48:05] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:48:15.480601 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:48:15.480676 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:48:15.503554 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc000154330), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:48:15]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:48:16] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:48:16] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 503 Service Unavailable]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 503 Service Unavailable]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:48:26.908130 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:48:26.908201 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:48:26.931611 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 503 Service Unavailable}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 503 Service Unavailable\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable get_network_details_error: Unable to get http request with 503 Service Unavailable]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc000012648), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable\n","        \t            \tget_network_details_error: Unable to get http request with 503 Service Unavailable)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:48:26]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:48:28] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:48:28] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 503 Service Unavailable]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 503 Service Unavailable]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 503 Service Unavailable]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:48:38.333417 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:48:38.333487 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:48:38.357068 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 503 Service Unavailable}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 503 Service Unavailable\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable get_network_details_error: Unable to get http request with 503 Service Unavailable]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:33\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc000152858), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \terror creating wallet%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable\n","        \t            \tget_network_details_error: Unable to get http request with 503 Service Unavailable)\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:48:38]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:48:39] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:48:39] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 503 Service Unavailable]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 503 Service Unavailable -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 503 Service Unavailable]\n","    utils.go:78: \u001b[32mCommand passed on retry [3/3]. Output: [No wallet in path  config/TestProtocolChallenge_wallet.json found. Creating wallet... -\u003cNEWLINE\u003e- ZCN wallet created!! -\u003cNEWLINE\u003e- Execute faucet smart contract success with txn :  614fddf22a4ffe3292170ae44164d1e73f3fb8ea5000698169ded80ee4b90117]\n","    zwalletcli_register_wallet_test.go:140: faucet output: [No wallet in path  config/TestProtocolChallenge_wallet.json found. Creating wallet... ZCN wallet created!! Execute faucet smart contract success with txn :  614fddf22a4ffe3292170ae44164d1e73f3fb8ea5000698169ded80ee4b90117]\n","    miner_block_rewards_test.go:485: list sharder nodes...\n","    zboxcli_stake_unstake_token_test.go:275: Requesting blobber list...\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:57\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould be true\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \tNo blobbers found in blobber list\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:48:52]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:48:54] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:48:54] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    zwalletcli_register_wallet_test.go:140: faucet output: [No wallet in path  config/TestProtocolChallenge_wallet.json found. Creating wallet... ZCN wallet created!! Execute faucet smart contract success with txn :  1062b5aa9684aa2337292a613054ebe0e19f39cc6f7ac44b8d566b601b142561]\n","    miner_block_rewards_test.go:485: list sharder nodes...\n","    zboxcli_stake_unstake_token_test.go:275: Requesting blobber list...\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:57\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould be true\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \tNo blobbers found in blobber list\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:48:57]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:48:58] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:48:58] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    zwalletcli_register_wallet_test.go:140: faucet output: [No wallet in path  config/TestProtocolChallenge_wallet.json found. Creating wallet... ZCN wallet created!! Execute faucet smart contract success with txn :  c27aa5089bb6189d2e6be2d87d8504fc55aebdff90e8c1223fdac4952aca4313]\n","    miner_block_rewards_test.go:485: list sharder nodes...\n","    zboxcli_stake_unstake_token_test.go:275: Requesting blobber list...\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:57\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould be true\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \tNo blobbers found in blobber list\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:49:01]\n","","","    system_test_framework.go:70: Test setup [Get list of sharders and blobbers] scheduled at [10-18-2023 12:49:03] \n","    system_test_framework.go:80: Test setup [Get list of sharders and blobbers] start at [10-18-2023 12:49:03] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    zwalletcli_register_wallet_test.go:140: faucet output: [No wallet in path  config/TestProtocolChallenge_wallet.json found. Creating wallet... ZCN wallet created!! Execute faucet smart contract success with txn :  cd2c14698ff38e3ce42d338fe64195a6bb1a5078c787784ac5620030a92c9b61]\n","    miner_block_rewards_test.go:485: list sharder nodes...\n","    zboxcli_stake_unstake_token_test.go:275: Requesting blobber list...\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:57\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:81\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould be true\n","        \tTest:       \tTestProtocolChallenge\n","        \tMessages:   \tNo blobbers found in blobber list\n","    system_test_framework.go:93: Test setup [Get list of sharders and blobbers] exit at [10-18-2023 12:49:06]\n",""],"Passed":false,"Skipped":false,"TestFileName":"0_challenge_protocol_test.go","TestFunctionDetail":{"Line":21,"Col":1}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"TestProtocolChallenge/Added_blobber_in_an_allocation_should_also_be_challenged_for_this_blobber_allocation","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":0,"Output":["","    0_challenge_protocol_test.go:138: Test case [Added blobber in an allocation should also be challenged for this blobber allocation] scheduled at [10-18-2023 12:45:50] \n","","","    system_test_framework.go:149: Test case [Added blobber in an allocation should also be challenged for this blobber allocation] start at [10-18-2023 12:45:50] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '6aec9fbdfc74b9f33851999ea2d1e19907ca2cea7971ea91e5cc8f45df2a522d' AND blobber_id = 'ff6424d80c49e57b7c2f0621b726f55efc6ca9ce327bdff89ef364adb8278b22'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:153\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \t\"0\" is not greater than \"0\"\n","        \tTest:       \tTestProtocolChallenge/Added_blobber_in_an_allocation_should_also_be_challenged_for_this_blobber_allocation\n","        \tMessages:   \tnumber of challenges should be greater than 0\n","    0_challenge_protocol_test.go:138: Test case [Added blobber in an allocation should also be challenged for this blobber allocation] exit at [10-18-2023 12:45:50]\n","","","    0_challenge_protocol_test.go:138: Test case [Added blobber in an allocation should also be challenged for this blobber allocation] scheduled at [10-18-2023 12:47:08] \n","","","    system_test_framework.go:149: Test case [Added blobber in an allocation should also be challenged for this blobber allocation] start at [10-18-2023 12:47:08] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '6aec9fbdfc74b9f33851999ea2d1e19907ca2cea7971ea91e5cc8f45df2a522d' AND blobber_id = 'ff6424d80c49e57b7c2f0621b726f55efc6ca9ce327bdff89ef364adb8278b22'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:153\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \t\"0\" is not greater than \"0\"\n","        \tTest:       \tTestProtocolChallenge/Added_blobber_in_an_allocation_should_also_be_challenged_for_this_blobber_allocation\n","        \tMessages:   \tnumber of challenges should be greater than 0\n","    0_challenge_protocol_test.go:138: Test case [Added blobber in an allocation should also be challenged for this blobber allocation] exit at [10-18-2023 12:47:08]\n","","","    0_challenge_protocol_test.go:138: Test case [Added blobber in an allocation should also be challenged for this blobber allocation] scheduled at [10-18-2023 12:48:52] \n","","","    system_test_framework.go:149: Test case [Added blobber in an allocation should also be challenged for this blobber allocation] start at [10-18-2023 12:48:52] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '6aec9fbdfc74b9f33851999ea2d1e19907ca2cea7971ea91e5cc8f45df2a522d' AND blobber_id = 'ff6424d80c49e57b7c2f0621b726f55efc6ca9ce327bdff89ef364adb8278b22'\n","    0_challenge_protocol_test.go:255: Challenges count: map[failed:0 open:0 passed:0 total:0]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:153\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \t\"0\" is not greater than \"0\"\n","        \tTest:       \tTestProtocolChallenge/Added_blobber_in_an_allocation_should_also_be_challenged_for_this_blobber_allocation\n","        \tMessages:   \tnumber of challenges should be greater than 0\n","    0_challenge_protocol_test.go:138: Test case [Added blobber in an allocation should also be challenged for this blobber allocation] exit at [10-18-2023 12:48:52]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"TestProtocolChallenge/Allocation_with_writes_and_deletes_should_not_get_challenges","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":0,"Output":["","    0_challenge_protocol_test.go:111: Test case [Allocation with writes and deletes should not get challenges] scheduled at [10-18-2023 12:45:50] \n","","","    system_test_framework.go:149: Test case [Allocation with writes and deletes should not get challenges] start at [10-18-2023 12:45:50] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '91d19d8b0636d63bf9d9aa7050fe49ea370d7d28344db33995723488acb09cf6'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:121\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould not be: 0\n","        \tTest:       \tTestProtocolChallenge/Allocation_with_writes_and_deletes_should_not_get_challenges\n","        \tMessages:   \tnumber of challenges should not be complete 0\n","    0_challenge_protocol_test.go:111: Test case [Allocation with writes and deletes should not get challenges] exit at [10-18-2023 12:45:50]\n","","","    0_challenge_protocol_test.go:111: Test case [Allocation with writes and deletes should not get challenges] scheduled at [10-18-2023 12:46:45] \n","","","    system_test_framework.go:149: Test case [Allocation with writes and deletes should not get challenges] start at [10-18-2023 12:46:45] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '91d19d8b0636d63bf9d9aa7050fe49ea370d7d28344db33995723488acb09cf6'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:121\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould not be: 0\n","        \tTest:       \tTestProtocolChallenge/Allocation_with_writes_and_deletes_should_not_get_challenges\n","        \tMessages:   \tnumber of challenges should not be complete 0\n","    0_challenge_protocol_test.go:111: Test case [Allocation with writes and deletes should not get challenges] exit at [10-18-2023 12:46:45]\n","","","    0_challenge_protocol_test.go:111: Test case [Allocation with writes and deletes should not get challenges] scheduled at [10-18-2023 12:48:26] \n","","","    system_test_framework.go:149: Test case [Allocation with writes and deletes should not get challenges] start at [10-18-2023 12:48:26] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '91d19d8b0636d63bf9d9aa7050fe49ea370d7d28344db33995723488acb09cf6'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:121\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould not be: 0\n","        \tTest:       \tTestProtocolChallenge/Allocation_with_writes_and_deletes_should_not_get_challenges\n","        \tMessages:   \tnumber of challenges should not be complete 0\n","    0_challenge_protocol_test.go:111: Test case [Allocation with writes and deletes should not get challenges] exit at [10-18-2023 12:48:26]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"TestProtocolChallenge/Allocation_with_writes_should_get_challenges","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":0,"Output":["","    0_challenge_protocol_test.go:97: Test case [Allocation with writes should get challenges] scheduled at [10-18-2023 12:45:50] \n","","","    system_test_framework.go:149: Test case [Allocation with writes should get challenges] start at [10-18-2023 12:45:50] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id='8971a7bcf56d2e0255194991b861fdf7b33b457b4535f603cdc731d112ca8efe'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:107\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \t\"0\" is not greater than \"0\"\n","        \tTest:       \tTestProtocolChallenge/Allocation_with_writes_should_get_challenges\n","        \tMessages:   \tnumber of challenges should be greater than 0\n","    0_challenge_protocol_test.go:97: Test case [Allocation with writes should get challenges] exit at [10-18-2023 12:45:50]\n","","","    0_challenge_protocol_test.go:97: Test case [Allocation with writes should get challenges] scheduled at [10-18-2023 12:46:33] \n","","","    system_test_framework.go:149: Test case [Allocation with writes should get challenges] start at [10-18-2023 12:46:33] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id='8971a7bcf56d2e0255194991b861fdf7b33b457b4535f603cdc731d112ca8efe'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:107\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \t\"0\" is not greater than \"0\"\n","        \tTest:       \tTestProtocolChallenge/Allocation_with_writes_should_get_challenges\n","        \tMessages:   \tnumber of challenges should be greater than 0\n","    0_challenge_protocol_test.go:97: Test case [Allocation with writes should get challenges] exit at [10-18-2023 12:46:33]\n","","","    0_challenge_protocol_test.go:97: Test case [Allocation with writes should get challenges] scheduled at [10-18-2023 12:48:15] \n","","","    system_test_framework.go:149: Test case [Allocation with writes should get challenges] start at [10-18-2023 12:48:15] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id='8971a7bcf56d2e0255194991b861fdf7b33b457b4535f603cdc731d112ca8efe'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:107\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \t\"0\" is not greater than \"0\"\n","        \tTest:       \tTestProtocolChallenge/Allocation_with_writes_should_get_challenges\n","        \tMessages:   \tnumber of challenges should be greater than 0\n","    0_challenge_protocol_test.go:97: Test case [Allocation with writes should get challenges] exit at [10-18-2023 12:48:15]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"TestProtocolChallenge/Canceled_allocation_should_no_more_get_any_challenges","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":0,"Output":["","    0_challenge_protocol_test.go:188: Test case [Canceled allocation should no more get any challenges] scheduled at [10-18-2023 12:45:50] \n","","","    system_test_framework.go:149: Test case [Canceled allocation should no more get any challenges] start at [10-18-2023 12:45:50] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '69affa381a16122db06ef1a5b3ade92c6aef25bedd6d29d768e693343e18da5f'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:198\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould not be: 0\n","        \tTest:       \tTestProtocolChallenge/Canceled_allocation_should_no_more_get_any_challenges\n","        \tMessages:   \tnumber of challenges should not be complete 0\n","    0_challenge_protocol_test.go:188: Test case [Canceled allocation should no more get any challenges] exit at [10-18-2023 12:45:50]\n","","","    0_challenge_protocol_test.go:188: Test case [Canceled allocation should no more get any challenges] scheduled at [10-18-2023 12:47:31] \n","","","    system_test_framework.go:149: Test case [Canceled allocation should no more get any challenges] start at [10-18-2023 12:47:31] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '69affa381a16122db06ef1a5b3ade92c6aef25bedd6d29d768e693343e18da5f'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:198\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould not be: 0\n","        \tTest:       \tTestProtocolChallenge/Canceled_allocation_should_no_more_get_any_challenges\n","        \tMessages:   \tnumber of challenges should not be complete 0\n","    0_challenge_protocol_test.go:188: Test case [Canceled allocation should no more get any challenges] exit at [10-18-2023 12:47:31]\n","","","    0_challenge_protocol_test.go:188: Test case [Canceled allocation should no more get any challenges] scheduled at [10-18-2023 12:49:01] \n","","","    system_test_framework.go:149: Test case [Canceled allocation should no more get any challenges] start at [10-18-2023 12:49:01] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '69affa381a16122db06ef1a5b3ade92c6aef25bedd6d29d768e693343e18da5f'\n","    0_challenge_protocol_test.go:255: Challenges count: map[failed:0 open:0 passed:0 total:0]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:198\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tShould not be: 0\n","        \tTest:       \tTestProtocolChallenge/Canceled_allocation_should_no_more_get_any_challenges\n","        \tMessages:   \tnumber of challenges should not be complete 0\n","    0_challenge_protocol_test.go:188: Test case [Canceled allocation should no more get any challenges] exit at [10-18-2023 12:49:01]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"TestProtocolChallenge/Challenges_success_rate_and_blobber_distribution_should_be_good","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":0,"Output":["","    0_challenge_protocol_test.go:202: Test case [Challenges success rate and blobber distribution should be good] scheduled at [10-18-2023 12:45:50] \n","","","    system_test_framework.go:149: Test case [Challenges success rate and blobber distribution should be good] start at [10-18-2023 12:45:50] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: \n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:206\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \texpected value must have a value other than zero to calculate the relative error\n","        \tTest:       \tTestProtocolChallenge/Challenges_success_rate_and_blobber_distribution_should_be_good\n","        \tMessages:   \tChallenge Failure rate should not be more than 5%\n","    0_challenge_protocol_test.go:202: Test case [Challenges success rate and blobber distribution should be good] exit at [10-18-2023 12:45:50]\n","","","    0_challenge_protocol_test.go:202: Test case [Challenges success rate and blobber distribution should be good] scheduled at [10-18-2023 12:47:42] \n","","","    system_test_framework.go:149: Test case [Challenges success rate and blobber distribution should be good] start at [10-18-2023 12:47:42] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: \n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:206\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \texpected value must have a value other than zero to calculate the relative error\n","        \tTest:       \tTestProtocolChallenge/Challenges_success_rate_and_blobber_distribution_should_be_good\n","        \tMessages:   \tChallenge Failure rate should not be more than 5%\n","    0_challenge_protocol_test.go:202: Test case [Challenges success rate and blobber distribution should be good] exit at [10-18-2023 12:47:42]\n","","","    0_challenge_protocol_test.go:202: Test case [Challenges success rate and blobber distribution should be good] scheduled at [10-18-2023 12:49:06] \n","","","    system_test_framework.go:149: Test case [Challenges success rate and blobber distribution should be good] start at [10-18-2023 12:49:06] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: \n","    0_challenge_protocol_test.go:255: Challenges count: map[failed:0 open:0 passed:0 total:0]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:206\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \texpected value must have a value other than zero to calculate the relative error\n","        \tTest:       \tTestProtocolChallenge/Challenges_success_rate_and_blobber_distribution_should_be_good\n","        \tMessages:   \tChallenge Failure rate should not be more than 5%\n","    0_challenge_protocol_test.go:202: Test case [Challenges success rate and blobber distribution should be good] exit at [10-18-2023 12:49:06]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"TestProtocolChallenge/Empty_Allocation_should_not_get_challenges","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":0,"Output":["","    0_challenge_protocol_test.go:125: Test case [Empty Allocation should not get challenges] scheduled at [10-18-2023 12:45:50] \n","","","    system_test_framework.go:149: Test case [Empty Allocation should not get challenges] start at [10-18-2023 12:45:50] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '6e23a95c5dcf71cd184a70a549d75daf3d81b7b3175fad1fc390f01fd221aa0a'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    0_challenge_protocol_test.go:125: Test case [Empty Allocation should not get challenges] exit at [10-18-2023 12:45:50]\n","","","    0_challenge_protocol_test.go:125: Test case [Empty Allocation should not get challenges] scheduled at [10-18-2023 12:46:56] \n","","","    system_test_framework.go:149: Test case [Empty Allocation should not get challenges] start at [10-18-2023 12:46:56] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '6e23a95c5dcf71cd184a70a549d75daf3d81b7b3175fad1fc390f01fd221aa0a'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    0_challenge_protocol_test.go:125: Test case [Empty Allocation should not get challenges] exit at [10-18-2023 12:46:56]\n","","","    0_challenge_protocol_test.go:125: Test case [Empty Allocation should not get challenges] scheduled at [10-18-2023 12:48:38] \n","","","    system_test_framework.go:149: Test case [Empty Allocation should not get challenges] start at [10-18-2023 12:48:38] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = '6e23a95c5dcf71cd184a70a549d75daf3d81b7b3175fad1fc390f01fd221aa0a'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    0_challenge_protocol_test.go:125: Test case [Empty Allocation should not get challenges] exit at [10-18-2023 12:48:38]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"TestProtocolChallenge/Number_of_challenges_between_2_blocks_should_be_equal_to_the_number_of_blocks_(given_that_we_have_active_allocations)","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":10.18,"Output":["","    0_challenge_protocol_test.go:60: Test case [Number of challenges between 2 blocks should be equal to the number of blocks (given that we have active allocations)] scheduled at [10-18-2023 12:45:50] \n","","","    system_test_framework.go:149: Test case [Number of challenges between 2 blocks should be equal to the number of blocks (given that we have active allocations)] start at [10-18-2023 12:45:50] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:46:00.818107 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:46:00.818159 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:46:00.843109 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:850\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:826\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/zboxcli_file_download_test.go:1323\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:61\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc000012150), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge/Number_of_challenges_between_2_blocks_should_be_equal_to_the_number_of_blocks_(given_that_we_have_active_allocations)\n","        \tMessages:   \tcreating wallet failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    0_challenge_protocol_test.go:60: Test case [Number of challenges between 2 blocks should be equal to the number of blocks (given that we have active allocations)] exit at [10-18-2023 12:46:00]\n","","","    0_challenge_protocol_test.go:60: Test case [Number of challenges between 2 blocks should be equal to the number of blocks (given that we have active allocations)] scheduled at [10-18-2023 12:46:12] \n","","","    system_test_framework.go:149: Test case [Number of challenges between 2 blocks should be equal to the number of blocks (given that we have active allocations)] start at [10-18-2023 12:46:12] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:46:22.370294 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:46:22.370517 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:46:22.394987 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:850\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:826\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/zboxcli_file_download_test.go:1323\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:61\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc000a300d8), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge/Number_of_challenges_between_2_blocks_should_be_equal_to_the_number_of_blocks_(given_that_we_have_active_allocations)\n","        \tMessages:   \tcreating wallet failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    0_challenge_protocol_test.go:60: Test case [Number of challenges between 2 blocks should be equal to the number of blocks (given that we have active allocations)] exit at [10-18-2023 12:46:22]\n","","","    0_challenge_protocol_test.go:60: Test case [Number of challenges between 2 blocks should be equal to the number of blocks (given that we have active allocations)] scheduled at [10-18-2023 12:47:53] \n","","","    system_test_framework.go:149: Test case [Number of challenges between 2 blocks should be equal to the number of blocks (given that we have active allocations)] start at [10-18-2023 12:47:53] \n","    zwalletcli_register_wallet_test.go:123: creating wallet...\n","    zboxcli_update_allocation_test.go:966: Executing faucet...\n","    utils.go:82: \u001b[33mCommand failed on attempt [1/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:82: \u001b[33mCommand failed on attempt [2/3] due to error [exit status 1]. Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:98: \u001b[31mCommand failed on final attempt [3/3] due to error [exit status 1]. Command String: [] Output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found -\u003cNEWLINE\u003e- get_network_details_error: Unable to get http request with 404 Not Found]\n","    utils.go:101: \u001b[31mThe verbose output for the command is:\n","    utils.go:105: \u001b[31m0chain-core-sdk [INFO]   2023/10/18 12:48:04.002355 wallet_base.go:327: ******* Wallet SDK Version:v1.10.0-70-g7f7e89b4 ******* (SetLogFile)\n","    utils.go:105: \u001b[31m0box-sdk [INFO]   2023/10/18 12:48:04.002539 sdk.go:79: ******* Storage SDK Version: v1.10.0-70-g7f7e89b4 *******\n","    utils.go:105: \u001b[31m0chain-core-sdk \u001b[31m[ERROR]  2023/10/18 12:48:04.026322 networkworker.go:51: Failed to update network details {error 26 0  get_network_details_error: Unable to get http request with 404 Not Found}\u001b[0m\n","    utils.go:105: \u001b[31mUpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","    utils.go:105: \u001b[31mget_network_details_error: Unable to get http request with 404 Not Found\n","    zwalletcli_register_wallet_test.go:140: faucet output: [UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found get_network_details_error: Unable to get http request with 404 Not Found]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:850\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/zboxcli_update_allocation_test.go:826\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/zboxcli_file_download_test.go:1323\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:61\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \tExpected nil, but got: \u0026exec.ExitError{ProcessState:(*os.ProcessState)(0xc00061a9c0), Stderr:[]uint8(nil)}\n","        \tTest:       \tTestProtocolChallenge/Number_of_challenges_between_2_blocks_should_be_equal_to_the_number_of_blocks_(given_that_we_have_active_allocations)\n","        \tMessages:   \tcreating wallet failed%!(EXTRA string=UpdateNetworkDetails: get_network_details_error: Unable to get http request with 404 Not Found\n","        \t            \tget_network_details_error: Unable to get http request with 404 Not Found)\n","    0_challenge_protocol_test.go:60: Test case [Number of challenges between 2 blocks should be equal to the number of blocks (given that we have active allocations)] exit at [10-18-2023 12:48:04]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]},{"FailureIndicator":"failed","SkippedIndicator":"","TestResults":[{"TestName":"TestProtocolChallenge/Replaced_blobber_in_an_allocation_should_not_be_challenged_for_this_blobber_allocation","Package":"github.com/0chain/system_test/tests/cli_tests","ElapsedTime":0,"Output":["","    0_challenge_protocol_test.go:157: Test case [Replaced blobber in an allocation should not be challenged for this blobber allocation] scheduled at [10-18-2023 12:45:50] \n","","","    system_test_framework.go:149: Test case [Replaced blobber in an allocation should not be challenged for this blobber allocation] start at [10-18-2023 12:45:50] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = 'fa2466b57759e8c3c00af4aaf12d389e28fcc1ebc29158363ffb0d4c6c0b3fa4' AND blobber_id = 'ff6424d80c49e57b7c2f0621b726f55efc6ca9ce327bdff89ef364adb8278b22'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:175\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \t\"0\" is not greater than \"0\"\n","        \tTest:       \tTestProtocolChallenge/Replaced_blobber_in_an_allocation_should_not_be_challenged_for_this_blobber_allocation\n","        \tMessages:   \tnumber of challenges should be greater than 0\n","    0_challenge_protocol_test.go:157: Test case [Replaced blobber in an allocation should not be challenged for this blobber allocation] exit at [10-18-2023 12:45:50]\n","","","    0_challenge_protocol_test.go:157: Test case [Replaced blobber in an allocation should not be challenged for this blobber allocation] scheduled at [10-18-2023 12:47:19] \n","","","    system_test_framework.go:149: Test case [Replaced blobber in an allocation should not be challenged for this blobber allocation] start at [10-18-2023 12:47:19] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = 'fa2466b57759e8c3c00af4aaf12d389e28fcc1ebc29158363ffb0d4c6c0b3fa4' AND blobber_id = 'ff6424d80c49e57b7c2f0621b726f55efc6ca9ce327bdff89ef364adb8278b22'\n","    0_challenge_protocol_test.go:259: all sharders gave an error at endpoint /count-challenges\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:175\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \t\"0\" is not greater than \"0\"\n","        \tTest:       \tTestProtocolChallenge/Replaced_blobber_in_an_allocation_should_not_be_challenged_for_this_blobber_allocation\n","        \tMessages:   \tnumber of challenges should be greater than 0\n","    0_challenge_protocol_test.go:157: Test case [Replaced blobber in an allocation should not be challenged for this blobber allocation] exit at [10-18-2023 12:47:19]\n","","","    0_challenge_protocol_test.go:157: Test case [Replaced blobber in an allocation should not be challenged for this blobber allocation] scheduled at [10-18-2023 12:48:57] \n","","","    system_test_framework.go:149: Test case [Replaced blobber in an allocation should not be challenged for this blobber allocation] start at [10-18-2023 12:48:57] \n","    0_challenge_protocol_test.go:230: Counting challenges with query: allocation_id = 'fa2466b57759e8c3c00af4aaf12d389e28fcc1ebc29158363ffb0d4c6c0b3fa4' AND blobber_id = 'ff6424d80c49e57b7c2f0621b726f55efc6ca9ce327bdff89ef364adb8278b22'\n","    0_challenge_protocol_test.go:255: Challenges count: map[failed:0 open:0 passed:0 total:0]\n","    assertions.go:333: \n","        \tError Trace:\t/root/actions-runner7/_work/system_test/system_test/tests/cli_tests/0_challenge_protocol_test.go:175\n","        \t            \t\t\t\t/root/actions-runner7/_work/system_test/system_test/internal/api/util/test/system_test_framework.go:150\n","        \t            \t\t\t\t/usr/local/go/src/runtime/asm_amd64.s:1598\n","        \tError:      \t\"0\" is not greater than \"0\"\n","        \tTest:       \tTestProtocolChallenge/Replaced_blobber_in_an_allocation_should_not_be_challenged_for_this_blobber_allocation\n","        \tMessages:   \tnumber of challenges should be greater than 0\n","    0_challenge_protocol_test.go:157: Test case [Replaced blobber in an allocation should not be challenged for this blobber allocation] exit at [10-18-2023 12:48:57]\n",""],"Passed":false,"Skipped":false,"TestFileName":"","TestFunctionDetail":{"Line":0,"Col":0}}]}]

    const report = window.GoTestReport({
                                         data: data,
                                         testResultsElem: document.getElementById('testResults'),
                                         testGroupListElem: document.getElementById('testGroupList')
                                       });


</script>
</body>
</html>
